export { default as Home } from './Home/Home'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as Checkout } from './Checkout/Checkout'
export { default as Orders } from './Orders/Orders'
export { default as Prime } from './Prime/Prime'
export { default as Mobiles } from './Mobile & Computer Collection/MobileComputer/Mobile'
export { default as Electronics } from './Electronics/Electronics/Electronics'
export { default as NewReleases } from './NewReleases/Newreleases/NewReleases'
export { default as Fashion } from './Fashion/Fashion/Fashion'
export { default as SportsFitness } from './Sports & Fitness/SportsFitness/SportsFitness'
export { default as HomeKitchen } from './Home & kitchen/HomeKitchen/HomeKitchen'
export { default as EchoAlexa } from './Echo & Alexa/EchoAlexa/EchoAlexa'
export { default as Computers } from './Mobile & Computer Collection/MobileComputer/Computer'
export { default as BestSellers } from './BestSellerCollection/BestSellers/BestSellers'
export { default as SingleProduct } from './SingleProduct/SingleProduct'

export { default as Payment } from './Payment/Payment'
export { default as AddressForm } from './Payment'
export { default as PaymentForm } from './PaymentForm'
export { default as Review } from './Review'
export { default as Mobile } from './SingleProduct/Mobile'
export { default as SingleProductElectronics } from './SingleProduct/Electronics'
export { default as SingleProductEchoAlexa } from './SingleProduct/EchoAlexa'
export { default as SingleProductNewReleases } from './SingleProduct/NewReleases'
export { default as SingleProductFashion } from './SingleProduct/Fashion'
export { default as SingleProductSportsFitness } from './SingleProduct/SportsFitness'
export { default as SingleProductHomeKitchen } from './SingleProduct/HomeKitchen'
export { default as Computer } from './SingleProduct/Computer'
export { default as SingleTrendingProduct } from './SingleProduct/SingleTrendingProduct'